### ISSUE TITLE
Making plank-themer compatible for packaging

### ISSUE THREAD

**Issue by orschiro** [rhoconlinux/plank-themer#1]
Hi there,

Thanks a lot for plank-themer!

It's a great tool and there was some [efforts](https://bbs.archlinux.org/viewtopic.php?pid=1424022#p1424022) to package it for Arch Linux.

However, it seems to be difficult as plank-themer is designed for almost everything to be in $HOME and could use a lot of cleanup.

Can you think of some code changes that would enhance the packaging?

Thanks ahead!

**Comment by rhoconlinux** [comment]
All I have to say is true! true! true!
^_^
I'll put some hands on this. Although my skills are really limited, I practically learned on the go with plank-themer how to do some stuff on bash (and I still learning). 

The cleaning is something that I can do. With time of course, but is a reallistic thing I can accomplish. 
The elegance of the code, on the other hand, I'm afraid I still have to learn how to make a program instead of trial and error. Anyway, I'll do my best. 

Regarding the packaging, sincerely it is ment to be in $HOME. All the stuff is there cause this is just a hack for the plank config. Besides this, I don't know what the packaging requirements are. How should I structure the thing and how can I improve something in order to make it more feasible to be packaged. 

If someone can help me, I'll be more than greatful. :+1:

**Comment by quequotion** [comment]
As a fellow novice, trial-and-error bash hacker, I'd like to help!

The thing to do here is install everything to /usr/share/plank(-themer) and add a (first run?) setup script that will copy needed files from the install location to ~/.config/plank.

This way it will be possible to avoid mixing up root and user command execution and file ownership.

I'll try a few things out during lunch!

**Comment by quequotion** [comment]
It took a little longer than lunch!

First, I reorganized much of the script into a makefile (the syntax is somewhat different from bash)
[Makefile](http://pastebin.com/FzjwqgyX)

Then, some of the script I split off into one the user can run by clicking on a Pantheon-themer icon in the application menu. This installs the dockitem.
[pantheon-themer.sh](http://pastebin.com/dRuy7c1A)

Simplified installation method:

```
git clone https://github.com/rhoconlinux/plank-themer.git && cd plank-themer 
cp path/to/Makefile path/to/plank-themer.sh ./ && make && make install
```

Run "Plank-themer" from the icon in the application menu to put the icon in the dock.

For now the community repository is installed without question; adding questions to makefiles seems difficult. I've posted the two files as patches here on Github as well; if they will be merged the installation procedure will be one step more simple:

```
git clone https://github.com/rhoconlinux/plank-themer.git && cd plank-themer && make && make install
```

**Comment by orschiro** [comment]
@quequotion 

Congratulation! Your improvements look very impressive. :)

**Comment by rhoconlinux** [comment]
awesome!!!!!!!! :+1:
Let me give a look at it, thank you very much!!!
:D
:dancer:

**Comment by orschiro** [comment]
Superb guys!

I just saw that there is already a package available in the AUR which installs perfectly!

https://aur.archlinux.org/packages/plank-themer-git/

Thanks again!

**Comment by orschiro** [comment]
@rhoconlinux 
@quequotion 

Can we close the issue?

**Comment by rhoconlinux** [comment]
thanks guys! :dancer:
