### ISSUE TITLE
Uninstall Plank Themer

### ISSUE THREAD

**Issue by ventouris** [rhoconlinux/plank-themer#4]
After following this

To proceed with the installation, open a Terminal in your Linux system. Then, paste this code to avoid dependencies problems:
`sudo apt-get install -y xterm`
and then paste this to install Plank Themer,
`cd ~ && mkdir -p ~/.temp-plank-themer && cd ~/.temp-plank-themer && wget https://github.com/rhoconlinux/plank-themer/archive/master.zip && unzip master.zip && cd plank-themer-master/ && rm -fR ~/.config/plank/dock1/theme_index; rm -fR ~/.config/plank/dock1/themes-repo; cp -a theme_index/ ~/.config/plank/dock1 && cp -a themes-repo/ ~/.config/plank/dock1 && cd ~ && rm -R ~/.temp-plank-themer && sh ~/.config/plank/dock1/theme_index/plank-on-dock-themer.sh`
Yes, you can close your terminal. :)

How can I remove it from my laptop?

**Comment by rhoconlinux** [comment]
just drag and drop the icon from plank. :)
Or...  To completely remove all the files, run the following command:

<pre>
cd ~ && rm -R $HOME/.config/plank/dock1/theme* && rm ~/.config/plank/dock1/launchers/plank-themer-ondock.dockitem
</pre>

In order to remove the additional themes installed, you should open a superuser nautilus entering <code>sudo nautilus</code> and then browsing to <code>/usr/share/plank/themes</code>. Just delete the folders you want to get rid of. :)

**Comment by Foggalong** [comment]
This should probably be stated on the website or in the README - I had trouble finding it because it's only available in a closed issue :P
